---
- name: Base OS configuration
  import_tasks: base.yml

- name: Package and update hardening
  import_tasks: packages.yml

#- name: Firewall hardening
#  import_tasks: firewall.yml

- name: SSH hardening
  import_tasks: ssh.yml
